### ISSUE TITLE
Any default config file for only semantic segmentation?

### ISSUE THREAD

**Issue by 6Zhiyu** [mapillary/seamseg#12]
Dear Author,

Thanks very much for your work, we can train and test on your code successfully. I just have a question that whether there is a default config file for only semantic segmentation? Because I have saw there are instance segmentation and object detection config file besides the Panoptic Segmentation config file.

Thanks.

**Comment by ducksoup** [comment]
We don't have segmentation only configuration files to share at this moment. However, in principle, any configuration that works for you for the Panoptic case should produce reasonable results when applied to pure segmentation (e.g. by setting the weights of all losses to 0, except the segmentation loss).
