### ISSUE TITLE
Get panoptic outputs

### ISSUE THREAD

**Issue by txfs1926** [mapillary/seamseg#20]
Hi, thanks for this great repo!
The script `test_panoptic.py` only generates the semantic prediction map for each input image instead of panoptic one. How can I obtain the prediction maps in panoptic format, like those ground truth `*_gtFine_instanceIds.png` of Cityscapes?
Thanks!

**Comment by txfs19260817** [comment]
BTW, when will the .pth.tar file to COCO-format panoptic predictions conversion script be released? Thanks.

**Comment by txfs1926** [comment]
Okay, I've written a script to achieve that.

**Comment by mahavir-GPI** [comment]
> Okay, I've written a script to achieve that.

Hey @txfs1926 I have been trying to visualize the Panoptic results with class labels but no luck so far, if possible can you please share your script.

**Comment by segermans** [comment]
> Okay, I've written a script to achieve that.

Hi @txfs1926, could you share your transformation script with us? Would be awesome!

**Comment by txfs19260817** [comment]
> > Okay, I've written a script to achieve that.
> 
> Hi @txfs1926, could you share your transformation script with us? Would be awesome!

Actually it's been nearly a year and I forgot a lot about this, but you might (might not) find some hints from my fork https://github.com/txfs19260817/seamseg or even from an application https://github.com/txfs19260817/seg-platform

**Comment by segermans** [comment]
> > > Okay, I've written a script to achieve that.
> > 
> > 
> > Hi @txfs1926, could you share your transformation script with us? Would be awesome!
> 
> Actually it's been nearly a year and I forgot a lot about this, but you might (might not) find some hints from my fork https://github.com/txfs19260817/seamseg or even from an application https://github.com/txfs19260817/seg-platform

Thanks!
