### ISSUE TITLE
when will be the test model released?

### ISSUE THREAD

**Issue by qiuhaining** [mapillary/seamseg#3]
I want to know the test result of your best model and do my research according to the result！Thank you'！

**Comment by ducksoup** [comment]
Pre-trained model is now available here: https://github.com/mapillary/seamseg#trained-models

**Comment by rotorliu** [comment]
@ducksoup 
Hello,
Can you provide another download url?
I can't touch google drive.

**Comment by haleqiu** [comment]
@ducksoup I am littler bit curious of the datasets you trained on, for this pre-trained model. 
COCO, CityScape and Mapillary?

**Comment by rotabulo** [comment]
@haleqiu the model was pre-trained on Mapillary and finetuned on cityscape. No Coco pretraining.
