### ISSUE TITLE
Pre-trained model download issue

### ISSUE THREAD

**Issue by rotorliu** [mapillary/seamseg#5]
Pre-trained model is now available here: https://github.com/mapillary/seamseg#trained-models

_Originally posted by @ducksoup in https://github.com/mapillary/seamseg/issues/3#issuecomment-521132717_

**Comment by rotorliu** [comment]
@ducksoup 
Hello,
Can you provide another download url?
I can't touch google drive.

**Comment by renxuezi** [comment]
@rotorliu Hi,Do you dowmload the pre-trained model sucessfully?
I have the same problem，could you please help me?
