### ISSUE TITLE
The config file about Cityscapes dataset

### ISSUE THREAD

**Issue by Shun14** [mapillary/seamseg#8]
Thank you for sharing your code.
Can you share the config file on the Cityscapes dataset? I just achieved the PQ=58.9 via the default config with 8gpus.

**Comment by hsfzxjy** [comment]
hi @Shun14 . Is your learning schedule following default config or paper?

**Comment by ducksoup** [comment]
@Shun14 @hsfzxjy Please note that, as highlighted in the README, the parameters in the default configuration files are just an indication of what a "reasonable" value for each parameter could be, and are not meant as a way to reproduce any of the results from our paper.

**Comment by HarisIqbal88** [comment]
@ducksoup would be great if you can share your config file for Cityscapes

**Comment by lxtGH** [comment]
@ducksoup Hi, Would you kindly share your config for Cityscapes for reproducing your results ?

**Comment by ducksoup** [comment]
@Shun14 @HarisIqbal88 @lxtGH Vistas and Cityscapes configuration files with the settings from our paper are now available in `scripts/configurations`.
